FROM andreasley/codespace_cpp_boost:ubuntu-22.04

# For reference, this is:
#
# FROM mcr.microsoft.com/vscode/devcontainers/cpp:ubuntu-22.04
# 
# # Install additional system packages.
# RUN apt-get update && \
#     export DEBIAN_FRONTEND=noninteractive && \
#     apt-get -y install --no-install-recommends build-essential libgmp-dev libyaml-cpp-dev
# 
# RUN curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz > premake-5.0.0-alpha16-linux.tar.gz && \
#     tar -zxf  premake-5.0.0-alpha16-linux.tar.gz -C tmp/  && \
#     cp tmp/premake5 usr/bin/
# 
# RUN vcpkg install boost-test boost-program-options boost-filesystem boost-format boost-lexical-cast boost-hana boost-mpi boost-property-tree boost-stacktrace boost-pfr boost-multiprecision boost-process boost-beast boost-iostreams boost-json